Models/Comic.cs
namespace SegundaPracticaFundamentos.Models
{
    public class Comic
    {
        public int IdComic { get; set; }
        public string Nombre { get; set; }
        public string Imagen { get; set; }
        public string Descripcion { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace SegundaPracticaFundamentos.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/ComicsController.cs
using Microsoft.AspNetCore.Mvc;
using SegundaPracticaFundamentos.Models;
using SegundaPracticaFundamentos.Repositories;

namespace SegundaPracticaFundamentos.Controllers
{
    public class ComicsController : Controller
    {
        IRepositoryComics repo;
        public ComicsController(IRepositoryComics repo)
        {
            this.repo = repo;
        }
        public IActionResult Index()
        {
            List<Comic> comics = this.repo.GetComics();
            return View(comics);
        }
        public IActionResult CreateLAMBDA()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateLAMBDA(Comic comic)
        {
            this.repo.InsertComicLambda(comic);
            return RedirectToAction("Index");
        }        
        public IActionResult CreatePROCEDURE()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreatePROCEDURE(Comic comic)
        {
            this.repo.InsertComicProcedure(comic);
            return RedirectToAction("Index");
        }
        public IActionResult Details()
        {
            List<Comic> comics = this.repo.GetComics();
            ViewData["COMICS"] = comics;
            return View();
        }
        [HttpPost]
        public IActionResult Details(int idComic)
        {
            List<Comic> comics = this.repo.GetComics();
            ViewData["COMICS"] = comics;
            Comic comic = this.repo.GetComic(idComic);
            return View(comic);
        }        
        public IActionResult Delete(int idComic)
        {
            Comic comic = this.repo.GetComic(idComic);
            
            return View(comic);
        }
        [HttpPost]
        public IActionResult Delete(Comic comic)
        {
            this.repo.DeleteComic(comic.IdComic);
            return RedirectToAction("Index");
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SegundaPracticaFundamentos.Models;
using System.Diagnostics;

namespace SegundaPracticaFundamentos.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Comics/CreateLAMBDA.cshtml
<h1>Nuevo Comic LAMBDA</h1>

<a asp-controller="Comics" asp-action="Index">
    Volver
</a>

<form method="post">
    <label>Nombre</label>
    <input type="text" class="form-control" name="nombre" />
    <label>Imagen</label>
    <input type="text" class="form-control" name="imagen" />
    <label>Descripcion</label>
    <input type="text" class="form-control" name="descripcion" />

    <button class="btn btn-outline-dark">
        Crear Comic
    </button>
</form>

Views/Comics/CreatePROCEDURE.cshtml
<h1>Nuevo Comic PROCEDURE</h1>

<a asp-controller="Comics" asp-action="Index">
    Volver
</a>

<form method="post">
    <label>Nombre</label>
    <input type="text" class="form-control" name="nombre" />
    <label>Imagen</label>
    <input type="text" class="form-control" name="imagen" />
    <label>Descripcion</label>
    <input type="text" class="form-control" name="descripcion" />

    <button class="btn btn-outline-dark">
        Crear Comic
    </button>
</form>

Views/Comics/Delete.cshtml
@model Comic
<h1>¿Eliminar Comic @Model.Nombre ?</h1>

<form method="post">
    <button class="btn btn-danger">
        Aceptar
    </button>
    <a asp-controller="Comics" asp-action="Index" class="btn btn-primary">
        Cancelar
    </a>
</form>

Views/Comics/Details.cshtml
@model Comic
@{
    List<Comic> comics = ViewData["COMICS"] as List<Comic>;
}
<a asp-controller="Comics" asp-action="Index">
    Volver
</a>

<h1>Selecciona un comic</h1>
<form method="post">
    <select class="form-select" name="idcomic">
        @foreach (Comic com in comics)
        {
            <option value="@com.IdComic">@com.Nombre</option>
        }
    </select>
    <button class="btn btn-outline-dark">Enviar</button>
</form>


@if(Model != null)
{
    <ul class="list-group">
        <li class="list-group-item">
            IdComic: @Model.IdComic
        </li>
        <li class="list-group-item">
            Nombre: @Model.Nombre
        </li>
        <li class="list-group-item">
            Imagen: <br />
            <img src="@Model.Imagen" style="width:150px;height:150px"/>
        </li>
        <li class="list-group-item">
            Descripcion: @Model.Descripcion
        </li>
    </ul>
}

Views/Comics/Index.cshtml
@model List<Comic>

<h1>Comics</h1>


<a asp-controller="Comics"
       asp-action="CreateLAMBDA">
        Crear Comic LAMBDA
    </a><br />
    <a asp-controller="Comics"
       asp-action="CreatePROCEDURE">
        Crear Comic PROCEDURE
    </a><br />
<a asp-controller="Comics"
       asp-action="Details">
        Detalles de Comic
    </a>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Imagen</th>
            <th>Descripción</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Comic comic in Model)
        {

            <tr>
                <td>@comic.Nombre</td>
                <td><img src="@comic.Imagen" style="width:150px;height:150px" /></td>
                <td>@comic.Descripcion</td>
                <td>
                    <a asp-controller="Comics" asp-action="Delete"
                       asp-route-idcomic="@comic.IdComic"
                       class="btn btn-danger">
                        Eliminar
                    </a>
                </td>
            </tr>

        }
    </tbody>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SegundaPracticaFundamentos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SegundaPracticaFundamentos.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SegundaPracticaFundamentos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Comics" asp-action="Index">Comics</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SegundaPracticaFundamentos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>